---
title: "MeOak's Resume"
---
PROFESIONAL EXPERIENCE

09/16 – 05/17
PBI Prep at Medgar Evers College, *Brooklyn, NY*
Supplemental Instruction Leader, Immunology and General Biology

04/12 – 08/15   Falcon Edge Capital, *New York, NY*

$3bn long/short equity hedge fund, Equity Research Assistant

	•	Managed equity research procurement and screening including liaising with external specialty consultants with special emphasis on healthcare, biotechnology, and pharmaceuticals sector
	•	Lead three-person team responsible for managing the office of Chief Executive Officer
	•	Assist General Counsel on SEC compliance procedures
	•	Consult on planning and strategy with Chief Operating Officer including employee on-boarding/off-boarding procedures


11/05 – 12/10	Sonenshine Partners										
New York, NY Executive Assistant to the Chairman & Founder of boutique investment bank

	•	Coordinate heavy calendar management, scheduling both professional and individual engagements for Chairman
	•	Prepared and edited client documents including engagement letters and non-disclosure agreements (NDA’s)
	•	Managed and updated marketing materials including pitch books and press packs by liaising with publications such as the Wall Street Journal, the New York Times, Thomson-Reuters
	•	Managed recruiting process by collaborating with recruiters at The Wharton School (Penn), Stern School of Business (NYU), and Columbia, managing candidate data, and organizing on-campus interviews
	•	Developed and executed various notable personal and executive events for:
	•	Former Reagan advisor Dr. Art Laffer, former Chairman of the Democratic National Committee Howard Dean, Governor Jack Markell (D-DE), Senator Mark Warner (D-VA), Brown University, Trinity College, Wynton Marsalis and Jazz @ Lincoln Center, and the International Center of Photography
	•	Responsibilities included site selection, contract negotiation, transportation arrangements, event material production, database management, and on-site management

08/05 – 11/05	Trinity School											New York, NY
Assistant Coach, Girls Varsity Volleyball, since 2003
			
11/04 – 10/05	Sun Capital Partners	 									New York, NY
Administrative Assistant to Managing Director of private equity firm

08/04 – 11/04	Hunter College											New York, NY
Student-Assistant Coach, Women’s Volleyball

01/04 – 07/04	Strategic Research Institute 									New York, NY
Marketing Assistant to Executive Vice President of conference planning organization 
	•	Assisted EVP in building industry specific business-to-business conferences by researching both popular topics of interest and potential conference exhibitors-sponsors

EDUCATION
CUNY – Medgar Evers College (2015-Present)									Brooklyn, NY
CUNY – Hunter College	(B.A. 2014)										New York, NY 	
Bronx High School of Science											Bronx, NY


ACTIVITIES & INTERESTS
Long-distance running, yoga, volleyball, Ultimate Frisbee, Bronx HS of Science Alumni Association

CUNY – City College, Assistant Coach, NCAA D-III Women’s Volleyball							2011
Trinity School, Assistant Coach, Varsity Girls Volleyball, New York, NY							2005
CUNY – Hunter College, Team Captain & MVP, NCAA D-III Women’s Volleyball						2003
